---
roles:
  - src: https://github.com/lbrick/ansible-capi-workload.git
    version: v0.4.4
    name: ansible-capi-workload

collections:
  - name: openstack.cloud
    version: 2.2.0
    type: galaxy
