---
- name: Workload | Get CAPI Managment cluster kubeconfig
  shell: >-
    kubectl get secret {{ capi_management_cluster }}-kubeconfig -o jsonpath='{.data.value}' | base64 --decode >> {{ tmp_dir }}/mgnt-kubeconfig

- name: Workload | Set CAPI Managment cluster kubeconfig as secret
  shell: >-
    kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig create secret generic kubeconfig --from-file=kubeconfig={{ tmp_dir }}/mgnt-kubeconfig -n kube-system

- name: Workload | Create auto-scaler deployment template
  template:
    src: "autoscaler-deployment.yml.j2"
    dest: "{{ tmp_dir }}/autoscaler-deployment.yml"
    mode: 0640

- name: Workload | Deploy auto-scaler for {{ cluster_name }}
  shell: >-
    kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply -f {{ tmp_dir }}/autoscaler-deployment.yml